version: "3.8"
services:
  yii2-app:
    image: subbusk/yii2-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:

