version: "3.8"
services:
  yii2-app:
    image: subbusk/yii2-app:latest
    environment:
      - YII_ENV=prod
      - YII_ENV_DEV=false
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  webnet:

