- hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
    - name: Start and enable NGINX
      systemd:
        name: nginx
        enabled: yes
        state: started

