name: Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install yii2-debug module (only for dev)
        if: github.ref != 'refs/heads/main'
        run: composer require --dev yiisoft/yii2-debug
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:latest -f docker/Dockerfile .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if sudo docker service inspect yii2-service > /dev/null 2>&1; then
               echo "Updating existing service..."
               sudo docker service update \
                  --image subbusk/yii2-app:latest \
                  --update-failure-action rollback \
                  yii2-service
            else
               echo "Creating new service..."
               sudo docker service create \
                 --name yii2-service \
                 --replicas 1 \
                 --publish 80:80 \
                 subbusk/yii2-app:latest
            fi

